<?php
//      Autogenerated Cache File
//      From www.phpBBDoctor.com
//      Last Cache Update NEVER

if (!defined('IN_PHPBB'))
{
	die('Hacking attempt');
}

// This is a basic empty cache that will be distributed
// with the MOD. This file should be overwritten as soon
// as a user sets up their first page permissions entry.
return;

//
//      End of Table Cache for phpbb_pages
//

?>
